PIA\appBundle\Entity\JobCustomProcs:
    type: entity
    table: job_custom_procs
    indexes:
        job_rule_id:
            columns:
                - job_rule_id
    uniqueConstraints:
        un_job_custom_proc:
            columns:
                - job_rule_id
                - script_lang_refid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        scriptLangRefid:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: script_lang_refid
        customProcName:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
            column: custom_proc_name
    manyToOne:
        jobRule:
            targetEntity: JobRules
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_rule_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
