PIA\appBundle\Entity\JobGroups:
    type: entity
    table: job_groups
    indexes:
        job_level_id:
            columns:
                - job_level_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        notes:
            type: string
            nullable: true
            length: 255
            fixed: false
    manyToOne:
        jobLevel:
            targetEntity: JobLevels
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_level_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
