PIA\appBundle\Entity\JobLevels:
    type: entity
    table: job_levels
    indexes:
        job_id:
            columns:
                - job_id
    uniqueConstraints:
        job_level_unq:
            columns:
                - job_id
                - level
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        level:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
    manyToOne:
        job:
            targetEntity: Jobs
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
