PIA\appBundle\Entity\JobMessages:
    type: entity
    table: job_messages
    indexes:
        link_id:
            columns:
                - link_id
        job_rule_id:
            columns:
                - job_rule_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        mtime:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
        message:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
    manyToOne:
        link:
            targetEntity: Links
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                link_id:
                    referencedColumnName: Id
            orphanRemoval: false
        jobRule:
            targetEntity: JobRules
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_rule_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
