PIA\appBundle\Entity\JobNodes:
    type: entity
    table: job_nodes
    indexes:
        job_rule_id:
            columns:
                - job_rule_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        tag:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
        index:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        tagId:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: tag_id
        class:
            type: string
            nullable: true
            length: 255
            fixed: false
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
    manyToOne:
        jobRule:
            targetEntity: JobRules
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_rule_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
