PIA\appBundle\Entity\JobRegexpTypeRef:
    type: entity
    table: job_regexp_type_ref
    id:
        id:
            type: boolean
            nullable: false
            default: '0'
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        refval:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
    lifecycleCallbacks: {  }
