PIA\appBundle\Entity\JobRuleLinks:
    type: entity
    table: job_rule_links
    indexes:
        job_rule_id:
            columns:
                - job_rule_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        level:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
    manyToOne:
        jobRule:
            targetEntity: JobRules
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_rule_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
