PIA\appBundle\Entity\JobRuleRecords:
    type: entity
    table: job_rule_records
    indexes:
        job_rule_id:
            columns:
                - job_rule_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        key:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
        typeRefid:
            type: boolean
            nullable: false
            default: '0'
            column: type_refid
    manyToOne:
        jobRule:
            targetEntity: JobRules
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                job_rule_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
