PIA\appBundle\Entity\JobRules:
    type: entity
    table: job_rules
    indexes:
        group_id:
            columns:
                - group_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
        containerOffset:
            type: integer
            nullable: true
            unsigned: false
            column: container_offset
        criticalType:
            type: boolean
            nullable: true
            column: critical_type
    manyToOne:
        group:
            targetEntity: JobGroups
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                group_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
