PIA\appBundle\Entity\Jobs:
    type: entity
    table: jobs
    indexes:
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        caption:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
        zeroLink:
            type: text
            nullable: false
            length: 65535
            fixed: false
            column: zero_link
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
