PIA\appBundle\Entity\Records:
    type: entity
    table: records
    indexes:
        IDX_9C9D5846ADA40271:
            columns:
                - link_id
    uniqueConstraints:
        record_unq:
            columns:
                - link_id
                - key
                - value_hash
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        num:
            type: integer
            nullable: false
            unsigned: true
            default: '1'
        key:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
        value:
            type: text
            nullable: false
            length: null
            fixed: false
        valueHash:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: ''
            column: value_hash
    manyToOne:
        link:
            targetEntity: Links
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                link_id:
                    referencedColumnName: Id
            orphanRemoval: false
    lifecycleCallbacks: {  }
