PIA\appBundle\Entity\TestLinks:
    type: entity
    table: test_links
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        link:
            type: text
            nullable: false
            length: 65535
            fixed: false
        lev:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
    lifecycleCallbacks: {  }
