PIA\appBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        username:
            columns:
                - username
        email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 25
            fixed: false
            default: ''
        password:
            type: string
            nullable: false
            length: 64
            fixed: false
            default: ''
        email:
            type: string
            nullable: false
            length: 60
            fixed: false
            default: ''
        isActive:
            type: boolean
            nullable: false
            default: '0'
            column: is_active
    lifecycleCallbacks: {  }
