# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    
    encoders:
        PIA\appBundle\Entity\Users:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: PIABundle:Users
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: pia_login
                check_path: pia_login
            logout:
                path:   /logout
                target: /    
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.+, roles: IS_AUTHENTICATED_FULLY }